export type ToolCategory =
  | 'ai-llm'
  | 'seo-data'
  | 'scraping'
  | 'google'
  | 'marketing-email'
  | 'social'
  | 'infrastructure'

export interface ToolMeta {
  service: string
  category: ToolCategory
  description: string
  pricingModel: 'free' | 'freemium' | 'usage-based' | 'subscription'
  pricingNotes: string
  competitors: string[]
  envVars: string[]
  docsUrl?: string
}

export const TOOL_METADATA: Map<string, ToolMeta> = new Map([
  // ── AI / LLM ──────────────────────────────────────────────────────────────
  ['fal.ai', {
    service: 'fal.ai',
    category: 'ai-llm',
    description: 'Serverless inference platform for image, video, and audio generation models. Hosts Kling, Flux, SDXL, and others with fast cold starts.',
    pricingModel: 'usage-based',
    pricingNotes: 'Pay-per-request. Image gen ~$0.003–0.05/image depending on model. Video gen ~$0.10–0.50/clip. No monthly minimum.',
    competitors: ['Replicate', 'Modal', 'RunPod', 'Together AI'],
    envVars: ['FAL_KEY'],
    docsUrl: 'https://fal.ai/docs',
  }],
  ['Replicate', {
    service: 'Replicate',
    category: 'ai-llm',
    description: 'Run open-source ML models via API. Large model library including image, video, audio, and language models.',
    pricingModel: 'usage-based',
    pricingNotes: 'Pay-per-second of compute. Typical image gen $0.0023–0.023/run. LLM inference priced per token.',
    competitors: ['fal.ai', 'Modal', 'Together AI', 'Hugging Face'],
    envVars: ['REPLICATE_API_TOKEN'],
    docsUrl: 'https://replicate.com/docs',
  }],
  ['OpenAI', {
    service: 'OpenAI',
    category: 'ai-llm',
    description: 'GPT-4o, GPT-image, Whisper, DALL-E, and Embeddings APIs. Industry-standard LLM and multimodal provider.',
    pricingModel: 'usage-based',
    pricingNotes: 'GPT-4o: $2.50/1M input tokens, $10/1M output. GPT-4o-mini: $0.15/$0.60. DALL-E 3: $0.04–0.08/image. Embeddings: $0.02/1M tokens.',
    competitors: ['Anthropic / Claude', 'Google Gemini', 'OpenRouter', 'Mistral'],
    envVars: ['OPENAI_API_KEY'],
    docsUrl: 'https://platform.openai.com/docs',
  }],
  ['Anthropic / Claude', {
    service: 'Anthropic / Claude',
    category: 'ai-llm',
    description: 'Claude Sonnet, Haiku, and Opus. Strong at coding, reasoning, and following complex instructions with long context windows.',
    pricingModel: 'usage-based',
    pricingNotes: 'Claude Sonnet 4.5: $3/1M input, $15/1M output. Haiku: $0.80/$4. Opus: $15/$75. Prompt caching reduces costs up to 90%.',
    competitors: ['OpenAI', 'Google Gemini', 'OpenRouter', 'Mistral'],
    envVars: ['ANTHROPIC_API_KEY'],
    docsUrl: 'https://docs.anthropic.com',
  }],
  ['Google Gemini', {
    service: 'Google Gemini',
    category: 'ai-llm',
    description: 'Gemini 1.5 Pro and Flash. Long context (up to 1M tokens), native multimodal, strong at structured outputs.',
    pricingModel: 'usage-based',
    pricingNotes: 'Gemini 1.5 Flash: $0.075/1M input, $0.30/1M output (under 128k). Free tier: 15 req/min. Pro: $3.50/$10.50/1M tokens.',
    competitors: ['OpenAI', 'Anthropic / Claude', 'OpenRouter'],
    envVars: ['GEMINI_API_KEY', 'GOOGLE_API_KEY'],
    docsUrl: 'https://ai.google.dev/docs',
  }],
  ['OpenRouter', {
    service: 'OpenRouter',
    category: 'ai-llm',
    description: 'Unified API proxy for 200+ LLMs including OpenAI, Anthropic, Google, Mistral, and open-source models. Single key, model routing.',
    pricingModel: 'usage-based',
    pricingNotes: 'Pass-through pricing at model provider rates, often with small markup. Useful for fallback routing and model comparison.',
    competitors: ['Direct provider APIs', 'Together AI', 'Anyscale'],
    envVars: ['OPENROUTER_API_KEY'],
    docsUrl: 'https://openrouter.ai/docs',
  }],

  // ── SEO & Data ────────────────────────────────────────────────────────────
  ['DataForSEO', {
    service: 'DataForSEO',
    category: 'seo-data',
    description: 'SERP data, keyword research, backlink analysis, and on-page SEO APIs. Pay-per-request with broad coverage across 70+ search engines.',
    pricingModel: 'usage-based',
    pricingNotes: 'SERP API: $0.0025–0.006/request. Keyword data: $0.0005/keyword. Backlinks: $0.001/domain. Minimum $50 deposit to start.',
    competitors: ['SEMrush', 'Ahrefs', 'Moz', 'SpyFu'],
    envVars: ['DATAFORSEO_LOGIN', 'DATAFORSEO_PASSWORD'],
    docsUrl: 'https://docs.dataforseo.com',
  }],
  ['Ahrefs', {
    service: 'Ahrefs',
    category: 'seo-data',
    description: 'Backlink index, keyword explorer, site audit, and rank tracker. Industry-leading backlink database.',
    pricingModel: 'subscription',
    pricingNotes: 'Lite: $129/mo. Standard: $249/mo. Advanced: $449/mo. Enterprise: custom. API access requires Advanced or Enterprise.',
    competitors: ['SEMrush', 'Moz', 'DataForSEO', 'Majestic'],
    envVars: ['AHREFS_API_KEY'],
    docsUrl: 'https://docs.ahrefs.com/api',
  }],
  ['SEMrush', {
    service: 'SEMrush',
    category: 'seo-data',
    description: 'All-in-one SEO platform: keyword research, competitor analysis, site audit, backlink tracking, PPC data.',
    pricingModel: 'subscription',
    pricingNotes: 'Pro: $139/mo. Guru: $249/mo. Business: $499/mo. API units sold separately; 1M units ~$50.',
    competitors: ['Ahrefs', 'Moz', 'DataForSEO', 'SpyFu'],
    envVars: ['SEMRUSH_API_KEY'],
    docsUrl: 'https://developer.semrush.com',
  }],
  ['Moz', {
    service: 'Moz',
    category: 'seo-data',
    description: 'Domain Authority, keyword difficulty, and link research API. Pioneer of DA metric widely used as proxy for site authority.',
    pricingModel: 'subscription',
    pricingNotes: 'Starter: $49/mo. Standard: $99/mo. Medium: $179/mo. Large: $299/mo. Mozscape API included in paid plans.',
    competitors: ['Ahrefs', 'SEMrush', 'DataForSEO'],
    envVars: ['MOZ_API_KEY', 'MOZ_SECRET_KEY'],
    docsUrl: 'https://moz.com/api',
  }],
  ['Firecrawl', {
    service: 'Firecrawl',
    category: 'scraping',
    description: 'Web scraping and crawling API that returns clean markdown. Handles JS rendering, anti-bot, sitemaps, and structured extraction.',
    pricingModel: 'freemium',
    pricingNotes: 'Free: 500 pages/mo. Hobby: $16/mo (3k pages). Standard: $83/mo (100k pages). Self-hostable open-source version available.',
    competitors: ['Apify', 'Diffbot', 'Jina Reader', 'Bright Data'],
    envVars: ['FIRECRAWL_API_KEY'],
    docsUrl: 'https://docs.firecrawl.dev',
  }],
  ['Apify', {
    service: 'Apify',
    category: 'scraping',
    description: 'Cloud scraping platform with 1,500+ pre-built actors. Covers Reddit, LinkedIn, Google Maps, Amazon, Instagram, and custom scrapers.',
    pricingModel: 'freemium',
    pricingNotes: 'Free: $5/mo compute credits. Starter: $49/mo. Scale: $499/mo. Actors billed per compute unit (~$0.25/CU). Many actors have per-result pricing.',
    competitors: ['Firecrawl', 'Bright Data', 'Oxylabs', 'ScrapingBee'],
    envVars: ['APIFY_API_TOKEN'],
    docsUrl: 'https://docs.apify.com',
  }],
  ['Bright Data', {
    service: 'Bright Data',
    category: 'scraping',
    description: 'Enterprise proxy network and web scraping infrastructure. Residential, datacenter, and mobile proxies. SERP and social media datasets.',
    pricingModel: 'usage-based',
    pricingNotes: 'Residential proxies: ~$8.40/GB. Datacenter: ~$0.60/GB. Datasets: custom pricing. Minimum commitment required for most plans.',
    competitors: ['Apify', 'Oxylabs', 'Smartproxy', 'Firecrawl'],
    envVars: ['BRIGHTDATA_USERNAME', 'BRIGHTDATA_PASSWORD', 'BRIGHTDATA_API_TOKEN'],
    docsUrl: 'https://docs.brightdata.com',
  }],

  // ── Google Services ───────────────────────────────────────────────────────
  ['Google Search Console', {
    service: 'Google Search Console',
    category: 'google',
    description: 'Official Google search performance data: impressions, clicks, CTR, position, and index coverage for your properties.',
    pricingModel: 'free',
    pricingNotes: 'Free. Requires OAuth2 and verified property ownership. API quota: 200 requests/day, 1200 rows/request.',
    competitors: ['Bing Webmaster Tools'],
    envVars: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'GOOGLE_REFRESH_TOKEN'],
    docsUrl: 'https://developers.google.com/webmaster-tools',
  }],
  ['Google Analytics / GA4', {
    service: 'Google Analytics / GA4',
    category: 'google',
    description: 'Event-based web analytics. Sessions, conversions, user journeys, audience segments, and custom reports via Data API.',
    pricingModel: 'free',
    pricingNotes: 'Free. GA4 360 (enterprise): custom pricing ~$50k+/yr. Data API: free with standard quotas (200k tokens/project/day).',
    competitors: ['Mixpanel', 'Plausible', 'PostHog', 'Amplitude'],
    envVars: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'GA4_PROPERTY_ID'],
    docsUrl: 'https://developers.google.com/analytics/devguides/reporting/data/v1',
  }],
  ['Google Sheets', {
    service: 'Google Sheets',
    category: 'google',
    description: 'Read/write spreadsheet data via API. Common output target for workflows — write results directly into client-shared sheets.',
    pricingModel: 'free',
    pricingNotes: 'Free with Google account. Quota: 300 requests/min/project. Workspace plans add storage/admin features.',
    competitors: ['Airtable', 'Notion', 'Excel Online'],
    envVars: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'GOOGLE_REFRESH_TOKEN'],
    docsUrl: 'https://developers.google.com/sheets/api',
  }],
  ['Google Docs', {
    service: 'Google Docs',
    category: 'google',
    description: 'Create and edit documents programmatically. Used for generating reports, briefs, and content deliverables in client-shared docs.',
    pricingModel: 'free',
    pricingNotes: 'Free with Google account. Same OAuth flow as Sheets.',
    competitors: ['Notion', 'Confluence', 'Coda'],
    envVars: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'GOOGLE_REFRESH_TOKEN'],
    docsUrl: 'https://developers.google.com/docs/api',
  }],
  ['Google Ads / Keyword Planner', {
    service: 'Google Ads / Keyword Planner',
    category: 'google',
    description: 'Keyword search volume, competition data, and CPC estimates from Google Ads. Requires active Google Ads account.',
    pricingModel: 'free',
    pricingNotes: 'Free with Google Ads account (spending not required but recommended to avoid throttling). API: free with approved developer token.',
    competitors: ['SEMrush', 'Ahrefs', 'DataForSEO', 'Ubersuggest'],
    envVars: ['GOOGLE_ADS_DEVELOPER_TOKEN', 'GOOGLE_ADS_CUSTOMER_ID', 'GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'],
    docsUrl: 'https://developers.google.com/google-ads/api',
  }],
  ['YouTube Data API', {
    service: 'YouTube Data API',
    category: 'google',
    description: 'Search videos, fetch channel stats, get transcripts, analyze comment sentiment. Used for competitor research and content strategy.',
    pricingModel: 'free',
    pricingNotes: 'Free. Quota: 10,000 units/day. Search costs 100 units/request; list operations 1–5 units. Quota increases available via request.',
    competitors: ['TubeBuddy API', 'vidIQ API'],
    envVars: ['YOUTUBE_API_KEY'],
    docsUrl: 'https://developers.google.com/youtube/v3',
  }],
  ['Google PageSpeed Insights', {
    service: 'Google PageSpeed Insights',
    category: 'google',
    description: 'Core Web Vitals, Lighthouse scores, and performance diagnostics for any URL. Uses real Chrome UX Report field data.',
    pricingModel: 'free',
    pricingNotes: 'Free. Quota: 25,000 requests/day with API key.',
    competitors: ['WebPageTest', 'GTmetrix', 'Pingdom'],
    envVars: ['PAGESPEED_API_KEY'],
    docsUrl: 'https://developers.google.com/speed/docs/insights/v5/get-started',
  }],
  ['Bing Webmaster Tools', {
    service: 'Bing Webmaster Tools',
    category: 'google',
    description: 'Bing search performance data, crawl diagnostics, and keyword research. Smaller but useful for full search coverage.',
    pricingModel: 'free',
    pricingNotes: 'Free. Requires site verification and API key from Bing Webmaster portal.',
    competitors: ['Google Search Console'],
    envVars: ['BING_WEBMASTER_API_KEY'],
    docsUrl: 'https://learn.microsoft.com/en-us/bingwebmaster/getting-access',
  }],
  ['Common Crawl', {
    service: 'Common Crawl',
    category: 'seo-data',
    description: 'Open repository of web crawl data. Petabytes of raw HTML, WARC files, and parsed text. Used for bulk link analysis and NLP training.',
    pricingModel: 'free',
    pricingNotes: 'Free to download. Hosted on AWS S3 — standard S3 data transfer costs apply if accessing outside us-east-1.',
    competitors: ['Bright Data', 'Apify'],
    envVars: [],
    docsUrl: 'https://commoncrawl.org/the-data/get-started',
  }],

  // ── Marketing / Email ─────────────────────────────────────────────────────
  ['Mailchimp', {
    service: 'Mailchimp',
    category: 'marketing-email',
    description: 'Email marketing platform with list management, campaigns, automations, and audience segmentation. Widely adopted by SMBs.',
    pricingModel: 'freemium',
    pricingNotes: 'Free: up to 500 contacts, 1k emails/mo. Essentials: $13/mo. Standard: $20/mo. Premium: $350/mo. Pricing scales with list size.',
    competitors: ['ConvertKit', 'Klaviyo', 'ActiveCampaign', 'HubSpot'],
    envVars: ['MAILCHIMP_API_KEY', 'MAILCHIMP_SERVER_PREFIX'],
    docsUrl: 'https://mailchimp.com/developer',
  }],
  ['ConvertKit', {
    service: 'ConvertKit',
    category: 'marketing-email',
    description: 'Creator-focused email platform with powerful automations, tagging, and segmentation. Popular with solopreneurs and content creators.',
    pricingModel: 'freemium',
    pricingNotes: 'Free: up to 10k subscribers (limited features). Creator: $25/mo (1k subs). Creator Pro: $50/mo. Scales with subscriber count.',
    competitors: ['Mailchimp', 'Beehiiv', 'Drip', 'ActiveCampaign'],
    envVars: ['CONVERTKIT_API_KEY', 'CONVERTKIT_API_SECRET'],
    docsUrl: 'https://developers.convertkit.com',
  }],
  ['HubSpot', {
    service: 'HubSpot',
    category: 'marketing-email',
    description: 'Full CRM platform: contacts, deals, email marketing, forms, workflows, and reporting. Free CRM tier is genuinely useful.',
    pricingModel: 'freemium',
    pricingNotes: 'CRM: free. Marketing Hub Starter: $18/mo. Professional: $800/mo. Enterprise: $3,600/mo. API free with any plan.',
    competitors: ['Mailchimp', 'ActiveCampaign', 'Salesforce', 'Pipedrive'],
    envVars: ['HUBSPOT_API_KEY', 'HUBSPOT_ACCESS_TOKEN'],
    docsUrl: 'https://developers.hubspot.com',
  }],
  ['Buffer', {
    service: 'Buffer',
    category: 'marketing-email',
    description: 'Social media scheduling and publishing. Supports LinkedIn, X/Twitter, Instagram, Facebook, TikTok, Pinterest, and Mastodon.',
    pricingModel: 'freemium',
    pricingNotes: 'Free: 3 channels, 10 scheduled posts. Essentials: $6/mo/channel. Team: $12/mo/channel. Agency: $120/mo (10 channels).',
    competitors: ['Hootsuite', 'Later', 'Sprout Social', 'Publer'],
    envVars: ['BUFFER_ACCESS_TOKEN'],
    docsUrl: 'https://buffer.com/developers/api',
  }],
  ['Hootsuite', {
    service: 'Hootsuite',
    category: 'marketing-email',
    description: 'Enterprise social media management. Scheduling, listening, analytics, and team collaboration across all major platforms.',
    pricingModel: 'subscription',
    pricingNotes: 'Professional: $99/mo. Team: $249/mo. Enterprise: custom. No free tier (free trial only). Generally overkill vs. Buffer for automation.',
    competitors: ['Buffer', 'Sprout Social', 'Later', 'Publer'],
    envVars: ['HOOTSUITE_ACCESS_TOKEN'],
    docsUrl: 'https://developer.hootsuite.com',
  }],

  // ── Social / Comms ────────────────────────────────────────────────────────
  ['Slack', {
    service: 'Slack',
    category: 'social',
    description: 'Send messages, notifications, and reports to Slack channels or DMs via webhook or Bot API. Common for workflow alerts and deliverables.',
    pricingModel: 'freemium',
    pricingNotes: 'Free: 90-day message history, 10 integrations. Pro: $8.75/user/mo. Business+: $15/user/mo. API is free with any plan.',
    competitors: ['Microsoft Teams', 'Discord', 'Google Chat'],
    envVars: ['SLACK_BOT_TOKEN', 'SLACK_WEBHOOK_URL'],
    docsUrl: 'https://api.slack.com',
  }],
  ['Reddit API', {
    service: 'Reddit API',
    category: 'social',
    description: 'Search posts/comments, monitor subreddits, and analyze community sentiment. Used for trend research and audience language analysis.',
    pricingModel: 'freemium',
    pricingNotes: 'Free tier: 100 requests/min (OAuth). Paid Data API: starts at $0.24/1k requests for >10M requests/mo. Most use cases fit free tier.',
    competitors: ['Apify Reddit scrapers', 'Bright Data'],
    envVars: ['REDDIT_CLIENT_ID', 'REDDIT_CLIENT_SECRET', 'REDDIT_USERNAME', 'REDDIT_PASSWORD'],
    docsUrl: 'https://www.reddit.com/dev/api',
  }],
  ['Twitter / X API', {
    service: 'Twitter / X API',
    category: 'social',
    description: 'Post tweets, search recent posts, monitor hashtags, and pull user timelines. API access has become significantly more restricted and expensive.',
    pricingModel: 'subscription',
    pricingNotes: 'Free: write-only (500 posts/mo). Basic: $100/mo (read limited). Pro: $5,000/mo. Enterprise: $42,000+/mo. Consider Apify scrapers as alternative.',
    competitors: ['Apify Twitter scrapers', 'Bright Data social datasets'],
    envVars: ['TWITTER_API_KEY', 'TWITTER_API_SECRET', 'TWITTER_BEARER_TOKEN', 'TWITTER_ACCESS_TOKEN', 'TWITTER_ACCESS_SECRET'],
    docsUrl: 'https://developer.twitter.com/en/docs',
  }],
  ['LinkedIn API', {
    service: 'LinkedIn API',
    category: 'social',
    description: 'Post content, read company pages, and manage marketing campaigns via LinkedIn Marketing API. Heavily restricted for third-party apps.',
    pricingModel: 'free',
    pricingNotes: 'Free with approved app. Marketing API requires LinkedIn partner approval. Most read access restricted — Apify actors often more practical.',
    competitors: ['Apify LinkedIn scrapers', 'PhantomBuster'],
    envVars: ['LINKEDIN_CLIENT_ID', 'LINKEDIN_CLIENT_SECRET', 'LINKEDIN_ACCESS_TOKEN'],
    docsUrl: 'https://learn.microsoft.com/en-us/linkedin',
  }],

  // ── Infrastructure ────────────────────────────────────────────────────────
  ['GitHub', {
    service: 'GitHub',
    category: 'infrastructure',
    description: 'Git hosting, repo management, and Actions CI/CD. Used for tracking upstream skill repos and triggering scan workflows.',
    pricingModel: 'freemium',
    pricingNotes: 'Free: unlimited public repos, 2k Actions minutes/mo. Team: $4/user/mo. Enterprise: $21/user/mo.',
    competitors: ['GitLab', 'Bitbucket', 'Azure DevOps'],
    envVars: ['GITHUB_TOKEN'],
    docsUrl: 'https://docs.github.com/en/rest',
  }],
])

export const CATEGORY_LABELS: Record<ToolCategory, string> = {
  'ai-llm': 'AI / LLM',
  'seo-data': 'SEO & Data',
  'scraping': 'Scraping',
  'google': 'Google Services',
  'marketing-email': 'Marketing & Email',
  'social': 'Social & Comms',
  'infrastructure': 'Infrastructure',
}

export const CATEGORY_COLORS: Record<ToolCategory, string> = {
  'ai-llm': 'bg-purple-900/40 text-purple-300 border-purple-800',
  'seo-data': 'bg-blue-900/40 text-blue-300 border-blue-800',
  'scraping': 'bg-orange-900/40 text-orange-300 border-orange-800',
  'google': 'bg-green-900/40 text-green-300 border-green-800',
  'marketing-email': 'bg-pink-900/40 text-pink-300 border-pink-800',
  'social': 'bg-cyan-900/40 text-cyan-300 border-cyan-800',
  'infrastructure': 'bg-gray-800 text-gray-300 border-gray-700',
}

export const PRICING_COLORS: Record<string, string> = {
  'free': 'text-green-400',
  'freemium': 'text-blue-400',
  'usage-based': 'text-amber-400',
  'subscription': 'text-red-400',
}
